# Paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  atlas_path: "data/atlas/BN_Atlas_246_2mm.nii"
  atlas_labels: "data/atlas/brainnetome_atlas.nii.gz"

# MATLAB/CAT12 Parameters
matlab:
  spm_path: "~/spm12"
  matlab_version: "R2023b"
  cat12_path: "~/spm12/toolbox/cat12"
  mni_template: "~/spm12/canonical/avg152T1.nii"
  smoothing_kernel: 8  # FWHM in mm

# Python Processing Parameters
preprocessing:
  registration_type: "SyN"
  interpolation: "Linear"
  bias_correction: True

# Feature Extraction
radiomics:
  features:
    - firstorder
    - glcm
    - glrlm
    - shape
  bin_width: 25
  symmetrical_glcm: True

# Model Parameters
svm:
  kernel: "rbf"
  cv_folds: 5
  param_grid:
    C: [0.1, 1, 10, 100]
    gamma: [0.001, 0.01, 0.1, 1]

# Statistical Analysis
bootstrap:
  n_iterations: 1000
  ci_level: 0.95 